import SchoolType from '../../src/types/SchoolType';

export const SCHOOL_DATA_RESPONSE: SchoolType = {
    created_at: '2002-11-02T00:00:00.000000',
    updated_at: '2003-03-02T00:00:00.000000',
    school_name: 'clonehigh',
    status: 'live',
    domains: ['https://cps-k12.org'],
    cohort_types: [],
    static_schedules: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
    school_title: 'Clone High School',
    nickname: 'CLone High',
    period_names: ['1', '2', '3', '4', '5', '6', '7', '8'],
    lunch_length: 25,
    lunch_wave_frequency: null,
    lunch_passing_time: null,
    lunch_waves: 3,
    lunch_first_wave_now: false,
    lunch_first_wave_now_offset: null,
    lunch_first_wave_pass: null,
    lunch_last_wave_pass: null,
    phone_number: '+1 (800) 000-0000',
    primary_color: null,
    dark_mode_color: null,
    students_count: 420,
    state: 'TX',
    district_code: 'clone_high_school_district_tx',
    county_code: null,
    timezone: 'US/Eastern',
    lat: 0,
    lng: 0,
    notes: null,
    schedule_tags: [],
    private: false,
    district_name: 'The Clone Distict',
    district_school_count: 1,
    meta: {
        free_period_course_id: 0,
        chat_minimum_depth: 0,
        user_count: 220,
        students_count: 420,
        features: {
            chat_tab: false,
            chat_unlocked: false,
            chat_unlocked_web: false,
            crush_copy: false,
            grade_chats: false,
            local_schedule_change: false,
            swap_courses_list_and_share_buttons: false,
            user_joined_class_notifications: false,
        },
    },
    users: [],
    staff: [],
};
